tasks:
  - init: |
      npm install -g pnpm
      pnpm install
    before: echo 'export GITPOD_URL="$(gp url 3000)"' >> $HOME/.bashrc
    command: pnpm dev

ports:
  - port: 3000
    onOpen: open-preview