tasks:
  - init: |
      npm install -g pnpm
      pnpm install    
    command: |
      echo 'export GITPOD_URL="$(gp url 3000)"' >> $HOME/.bashrc
      source $HOME/.bashrc
      npm run dev

ports:
  - port: 3000
    onOpen: open-preview