name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Echo github.ref
        shell: bash
        run: echo "${{ github.ref }}"
        id: extract_branch
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install vercel
        run: npm install vercel
      - name: Deploy
        run: >
          vc --prod --confirm
          --token ${{ secrets.ZEIT_TOKEN }}
